In [5]:
import numpy as np

In [6]:
lista = [1, 2, 3, 4, 5, 6]

array = np.array(lista)

In [7]:
print(type(lista))
print(type(array))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
array[0] = 9
print(array)

[9 2 3 4 5 6]


In [10]:
# Matrizes
matriz_zeros = np.zeros((5, 3))
print(matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# Notas de alunos
lista_de_notas = [9.8, 5.6, 7.8, 9.1, 6.5]

notas = np.array(lista_de_notas)

In [12]:
print('A nota máxima é:', notas.max())
print('A nota mínima é:', notas.min())
print('Desvio padrão é:', notas.std())
print('A média é:', notas.mean())
print('A posição do menor é:', notas.argmin())

A nota máxima é: 9.8
A nota mínima é: 5.6
Desvio padrão é: 1.5628179676469045
A média é: 7.76
A posição do menor é: 1


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [28]:
notas = np.array([])

for c in range(1, 4):
     aluno = float(input('Digite a {}° nota: '.format(c)))
     notas = np.append(notas, aluno)

print('A média é {}'.format(notas.mean()))
print('O desvio padrão é {}'.format(notas.std()))

Digite a 1° nota:  4
Digite a 2° nota:  6
Digite a 3° nota:  10


A média é 6.666666666666667
O desvio padrão é 2.494438257849294
